server:
  port: 8080
  host: 0.0.0.0

#dataSource:
#  jdbcUrl: "jdbc:postgresql://tfb-database:5432/hello_world"
#  username: benchmarkdbuser
#  password: benchmarkdbpass

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://tfb-database:5432/hello_world"
#    url: "jdbc:postgresql://localhost:5432/hello_world"
    username: "benchmarkdbuser"
    password: "benchmarkdbpass"
    poolName: hikariPool
    maximumPoolSize: 32
#    initializationFailTimeout: -1
#    connectionTimeout: 5000
  statements:
#    ping: "DO 0"
#    select-all-pokemons: "SELECT id, name FROM Pokemons"